namespace DataConsulting.PuntoVentaComercial.Domain.Enums
{
    public enum ECabeceraVentaSQL : byte
    {
        IdEmpresa = 0,
        IdDocumento = 1,
        DocumentoNombre = 2,
        DocumentoSiglas = 3,
        ClienteNumero = 4,
        NombreCliente = 5,
        IdDocumentoIdentidad = 6,
        DocumentoIdentidadNombre = 7,
        Longitud = 8,
        Direccion = 9,
        IdTipoMoneda = 10,
        TipoMonedaNombre = 11,
        MotivoNotaNombre = 12,
        MotivoCodigoSunat = 13,
        NumSerieCliente = 14,
        NumDocumentoCliente = 15,
        FechaEmision = 16,
        FormaPago = 17,
        Observaciones = 18,
        Estado = 19,
        IdVentaScop = 20,
        IdDocRef = 21,
        ISC = 22,
        IGV = 23,
        DescuentoGlobal = 24,
        ValorAfecto = 25,
        ValorInafecto = 26,
        ValorExonerado = 27,
        ValorRegalo = 28,
        ImporteTotal = 29,
        NombreArchivoXML = 30,
        NombreRespuestaXML = 31,
        CodigoSunat = 32,
        EstadoSunat = 33,
        RucEmpresa = 34,
        TipoIgv = 35,
        FlagComercioExterior = 36
    }

    public enum EDetalleVentaSQL : byte
    {
        IdEmpresa = 0,
        IdVentaScop = 1,
        Correlativo = 2,
        ArticuloNombre = 3,
        UnidadNombre = 4,
        SiglaUnidad = 5,
        UnidadCodSunat = 6,
        Cantidad = 7,
        PrecioUnitario = 8,
        TipoPrecio = 9,
        Descuento = 10,
        SubTotal = 11,
        Estado = 12
    }

    public enum EColumnaCabecera : int
    {
        IdTipoDocumento = 0,
        NombreCliente = 1,
        IdDocumentoIdentidad = 2,
        NumDocumentoCliente = 3,
        DireccionCliente = 4,
        NombreCliente2 = 5,
        IdDocumentoIdentidad2 = 6,
        NumDocumentoCliente2 = 7,
        DireccionCliente2 = 8,
        IdTipoMoneda = 9,
        NombreMotivoNota = 10,
        CodSunatMotivo = 11,
        SerieNumerica = 12,
        NumeroNumerico = 13,
        SerieAlfanumerica = 14,
        NumeroAlfanumerico = 15,
        FechaEmision = 16,
        FormaPago = 17,
        Observaciones = 18,
        Estado = 19,
        SerieNumericaReferencia = 20,
        NumeroNumericoReferencia = 21,
        SerieAlfaReferencia = 22,
        NumeroAlfaReferencia = 23,
        IdTipoDocumentoRef = 24,
        ISC = 25,
        IGV = 26,
        DescuentoGlobal = 27,
        ValorAfecto = 28,
        ValorInafecto = 29,
        ValorExonerado = 30,
        ValorRegalo = 31,
        ValorDonacion = 32,
        ImporteTotal = 33,
        TipoVenta = 34,
        ToTalDescuento = 35,
        TipoIgv = 36,
        //HOTELERIA
        PorcentajeServicio = 37,
        MontoServicio = 38,
        FechaIngresoPais = 39,
        FechaIngresoHospedaje = 40,
        FechaSalidaHospedaje = 41,
        DiasPermanencia = 42,
        PaisPasaporte = 43,
        CodNacionalidadPasaporte = 44,
        CodSunatPaisPasporte = 45,
        PaisResidencia = 46,
        CodNacionalidadResidencia = 47,
        CodSunatPaisResidencia = 48,
        AgenciaViaje = 49,
        RUCAgenciaViaje = 50,
        Reserva = 51,
        VisualizarFechasHospedaje = 52,
        //REPUESTOS
        DescripcionServicio = 53,
        //AUTO
        Marca = 54,
        SerieVIN = 55,
        Version = 56,
        AnioFabricacion = 57,
        Motor = 58,
        Combustible = 59,
        Cilindros = 60,
        Traccion = 61,
        NroRuedas = 62,
        NroEjes = 63,
        Ancho = 64,
        Largo = 65,
        Alto = 66,
        Modelo = 67,
        Categoria = 68,
        AnioModelo = 69,
        Color = 70,
        Carroceria = 71,
        Cilindrada = 72,
        Transmision = 73,
        PotenciaHP = 74,
        PotenciaKM = 75,
        TipoNeumatico = 76,
        DistanciaEjes = 77,
        Puertas = 78,
        //EXPORTACION
        PaisDestino = 79,
        CodNacionalidadDestino = 80,
        CodSunatPaisDestino = 81,
        NroGuia = 82,
        Consignatario = 83,
        DireccionConsigntario = 84,
        TerminosComercializacion = 85,
        RegUnifInd = 86,
        PesoBruto = 87,
        PesoNeto = 88,
        MedioTransporte = 89,
        PuertoEmbarque = 90,
        PuertoDestino = 91,
        Flete = 92,
        Incoterm = 93,
        SiglasIncoterm = 94,
        UMPesoBruto = 95,
        SiglasUMPesoBruto = 96,
        CodSunatUMPesoBruto = 97,
        UMPesoNeto = 98,
        SiglasUMPesoNeto = 99,
        CodSunatUMPesoNeto = 100,
        //COMPLEMENTARIOS
        NroPlaca = 101,
        NotaAdicional = 102,
        SerieRefNoExistente = 103,
        NumeroRefNoExistent = 104,
        IdTipoDocumentoRefNoExistent = 105,
        ClienteConsumidorFinal = 106,
        ClienteTipoAgente = 107,
        ImportePercepcion = 108,
        NumeroCuotas = 109,
        OrdenCompra = 110,
        FechaVencimiento = 111,
        ValorICBPER = 112,
        FlagDetraccion = 113,
        CodigoDetraccion = 114,
        TasaDetraccion = 115,
        MontoDetraccion = 116
    }

    public enum EColumnaDetalle : int
    {
        NombreArticulo = 0,
        NombreUnidad = 1,
        SiglasUnidad = 2,
        CodSunatUnidad = 3,
        Cantidad = 4,
        PrecioUnitario = 5,
        TipoPrecio = 6,
        Descuento = 7,
        SubTotal = 8,
        CodArticulo = 9,
        FlagDescuento = 10,
        MontoISC = 11,
        PorcentajeISC = 12,
        ValorVentaBruto = 13,
        MontoServicio = 14,
        MontoIGV = 15,
        //AUTO
        DesServicioAuto = 16,
        TipoISC = 17,
        //PERCEPCION
        PorcentajePercepcion = 18,
        MontoMinimoConsumidorFinal = 19,
        TipoPercepcion = 20,
        PorcentajePercepcionVenta = 21,
        ImportePercepcion = 22,
        //CODIGO UNSPSC
        CodigoUNSPSC = 23,
        //Impuesto a la bolsa de plástico
        ValorICBPER = 24
    }
}
